### ISSUE TITLE
Destructuring of Arrays Doesn't Seem to Work

### ISSUE THREAD

**Issue by nickreese** [Rich-Harris/object-cull#4]
Hey Rich, love the tool. Just a quick note that:

```

const proxy = prepare(obj)

const [one, two, three] = proxy;

```

Wasn't working  in my code. When I switched to a different method of unpacking the array, things worked fined. 

Thanks dude.

**Comment by Rich-Harris** [comment]
Thanks! Learned something new about proxies and destructuring. Fixed in 1.1.1
